[project]
name = "datatrax-jcr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dxbhans", email = "dxbhans@gmail.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "duckdb>=1.5.6",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.4",
    "pyyaml>=6.0.3",
]

[project.scripts]
datatrax-jcr = "datatrax_jcr:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
